# Generated by Django 5.1.7 on 2025-03-24 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('center_latitude', models.FloatField()),
                ('center_longitude', models.FloatField()),
                ('default_zoom', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('excel', 'Excel File'), ('kml', 'KML File')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='property_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'kml', 'kmz'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_errors', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='maps.region')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=100)),
                ('matricule_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('boundary_coordinates', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('building_area', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('last_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('predicted_height', models.FloatField(blank=True, null=True)),
                ('predicted_quality_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='maps.propertydatafile')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='maps.region')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='maps.property')),
            ],
            options={
                'unique_together': {('property', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['lot_number'], name='maps_proper_lot_num_fb4c31_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['matricule_number'], name='maps_proper_matricu_6c1ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['address'], name='maps_proper_address_07694f_idx'),
        ),
    ]
