# Generated by Django 5.1.7 on 2025-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_maplayer_shapefile_dir_alter_maplayer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='onedrive_file_id',
            field=models.CharField(blank=True, help_text='File ID in OneDrive', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='onedrive_file_name',
            field=models.CharField(blank=True, help_text='Original file name in OneDrive', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='onedrive_file_url',
            field=models.URLField(blank=True, help_text='Download URL for OneDrive file', null=True),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('onedrive', 'OneDrive')], default='local', help_text='Storage location for the file', max_length=10),
        ),
    ]
