# Generated by Django 5.1.7 on 2025-03-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_maplayer_onedrive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplayer',
            name='onedrive_file_url',
            field=models.TextField(blank=True, help_text='Download URL for OneDrive file', null=True),
        ),
    ]
